# Containers Docker Compose will manage
services:

  #database servicve
  #name we chose for this database service
  db:
    #use an existing PostgreSQL image that already includes pgvector (instead of builing ourselves)
    image: pgvector/pgvector:pg16

    # Environment variables used to initialize PostgreSQL
    environment:
      # Initial database Docker/PostgreSQL creates
      POSTGRES_DB: codebase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    #volume = so that the PostgreSQL data survives even if the database container is deleted and recreated
    #w/o a volume = deleting the database containere = delete its database file too
    volumes:
      # postgres_data is the named volume
      # /var/lib/postgresql/data is where PostgreSQL stores its data inside the container
      - postgres_data:/var/lib/postgresql/data

    ports:
      #Mac port 5432 -> database container port 5432
      - "5432:5432"

    # database health check 
    # healthcheck = defines how Docker checks the container's health 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d codebase"]
      interval: 5s
      timeout: 5s
      retries: 5
    #interval = run the check every 5s, fail a check if it takes longer than 5 seconds
    #retries = after 5 failchecks, marh the container as unhealthy

  #backend service
  backend:
    #use the Dockerfile in the current project dir
    build: .
    
    #pass your .env values into the backend container
    env_file:
      - .env
    
    # mac port 5001 to backend container port 5001
    ports:
      - "5001:5001"

    # make database migration Automatic so we don't have to manually run
    #this command = overrides the Dockerfile CMD, thus must add python ....py to run Flask
    command: sh -c "alembic upgrade head && python flask_main.py"

    # starts the db container first
    depends_on: 
      db: 
        #depends on db being healthy (do not start backend until db passes its healthcheck)
          condition: service_healthy 

    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:5001/health"] to do this, backend need to install curl
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5001/health')"]
      interval: 5s
      timeout: 5s
      retries: 5

      #gives grace perid to the backend (since backend loads the embedding model at start up, may need more time before /heath becomes available)
      start_period: 30s

  #frontend servive
  frontend:
    #use the Dockerfile in the /frontend folder 
    build: ./frontend

    # expose the Vite frontend port 
    ports:
      - "5173:5173"

    #make the Compose starts backend before frontend
    depends_on:
      backend:
        condition: service_healthy

#tells Compose to create/manage a Dockere volume named postgres_data
volumes:
  postgres_data:



#docker compose exec backend alembic upgrade head
