"""update repository file and chunk tables

Revision ID: 1f17cae54448
Revises: d32d9e7d3cf0
Create Date: 2026-08-02 13:14:51.037576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '1f17cae54448'
down_revision: Union[str, Sequence[str], None] = 'd32d9e7d3cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('class_name', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('func_name', sa.String(), nullable=True))
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.drop_column('chunks', 'func_or_class_name')
    op.add_column('files', sa.Column('path', sa.String(), nullable=False))
    op.add_column('files', sa.Column('name', sa.String(), nullable=False))
    op.add_column('files', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('repositories', sa.Column('github_url', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('name', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('owner', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('default_branch', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('latest_commit_sha', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('ingestion_status', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('repositories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'updated_at')
    op.drop_column('repositories', 'created_at')
    op.drop_column('repositories', 'ingestion_status')
    op.drop_column('repositories', 'latest_commit_sha')
    op.drop_column('repositories', 'default_branch')
    op.drop_column('repositories', 'owner')
    op.drop_column('repositories', 'name')
    op.drop_column('repositories', 'github_url')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'size_bytes')
    op.drop_column('files', 'name')
    op.drop_column('files', 'path')
    op.add_column('chunks', sa.Column('func_or_class_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=False)
    op.drop_column('chunks', 'func_name')
    op.drop_column('chunks', 'class_name')
    # ### end Alembic commands ###
